project:
  name: quickstart-tibco-data-science
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
  - ap-northeast-1
  - ap-southeast-1
  - ap-southeast-2
  - eu-central-1
  - eu-west-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  s3_bucket: ''
tests:
  tibco-ds:
    parameters:
      AdminConsoleAccessCIDR: 10.0.0.0/16
      AvailabilityZones: $[taskcat_genaz_2]
      BastionAMIOS: Amazon-Linux2-HVM
      BastionInstanceType: t2.micro
      EMRClusterName: $[taskcat_random-string]
      EMRCoreNodes: '1'
      KeyPairName: $[taskcat_getkeypair]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      QSS3KeyPrefix: quickstart-tibco-data-science/
      RDSPassword: $[taskcat_genpass_12A]
      TSDSInstanceName: $[taskcat_random-string]
      TSDSInstancePassword: $[taskcat_genpass_12A]
      TSDSInstanceType: m5.2xlarge
      TSDSowner: $[taskcat_random-string]
    regions:
    - ap-northeast-1
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - eu-west-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    s3_bucket: ''
    template: templates/tibco-data-science-master.template.yaml
